---
- name: Install apache httpd (state=present is optional)
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add debian repo
  deb822_repository:
    name: debian
    types: deb
    uris: https://deb.debian.org/debian
    suites: bookworm bookworm-updates
    components:
      - main
      - contrib
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    
- name: Add debian Security repo
  deb822_repository:
    name: debian-security
    types: deb
    uris: https://security.debian.org/debian-security
    suites:  bookworm-security
    components:
      - main
      - contrib
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Remove Old and Ugly default apt sources.list
  ansible.builtin.file:
    dest: /etc/apt/sources.list
    state: absent    

- name: Update apt cache
  ansible.builtin.apt:
    name: "*"
    update_cache: yes

- name: apt install unattended-upgrades,needrestart
  ansible.builtin.apt:
    name: 
      - unattended-upgrades
      - needrestart
    state: present

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: 'APT::Periodic::Unattended-Upgrade "1";'
    create: yes
