---

- name: Add debian repo
  deb822_repository:
    name: debian
    types: deb deb-src
    uris: http://deb.debian.org/debian
    suites: bookworm bookworm-updates
    components:
      - main
      - contrib
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

  
- name: Add debian Security repo
  deb822_repository:
    name: debian
    types: deb deb-src
    uris: http://deb.debian.org/debian
    suites:  bookworm-security
    components:
      - main
      - contrib
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Set up Debian 12 default apt sources.list
  ansible.builtin.file:
    dest: /etc/apt/sources.list
    state: absent    

- name: Update apt cache
  ansible.builtin.apt:
    name: "*"
    update_cache: yes

- name: apt install unattended-upgrades,needrestart
  ansible.builtin.apt:
    name: 
      - unattended-upgrades
      - needrestart
    state: present

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: 'APT::Periodic::Unattended-Upgrade "1";'
    create: yes

- name: Removes a cron file from under /etc/cron.d
  ansible.builtin.cron:
    name: set_apt_cfg
    cron_file: ansible_yum-autoupdate
    state: absent


- name: Set up Cron, send mail on error 
  ansible.builtin.cron:
    name: "Set Debian Update Configuration"
    minute: "0"
    hour: "5"
    job: 'ansible-pull -U https://github.com/jijischmitt/cfg_debian.git -C main cfg_debian.yml >/tmp/ansible-pull.log 2>&1 & if [ $? -ne 0 ]; then cat /tmp/ansible-pull.log | mail -s "Ansible Pull Error" root; fi '
    user: root
    cron_file: check_reboot
