---
- name: Check if reboot file exists
  stat:
    path: /var/run/reboot-required
  register: reboot_result

- name: Check if a restart is needed
  shell: "needrestart -b 2> >(grep -q NEEDRESTART-SVC)"
  register: restart_check
  ignore_errors: true # Allow the task to continue even if grep fails (no restart needed)

- name: Reboot 
  reboot:
  when: restart_check.rc == 0
